/* =========================================================================
   BeamDrive Mobile — GLSL ES 3.00 shader sources
   One uber-shader for surfaces, a depth-only pass for shadows, an analytic
   sky, and the post chain (bright / blur / composite).
   ========================================================================= */
(function () {
  'use strict';

  var S = {};
  B.Shaders = S;

  /* ------------------------------------------------------ shared snippets */

  var COMMON = [
    'const float PI = 3.14159265359;',
    '',
    'float hash11(float p){ p = fract(p*0.1031); p *= p+33.33; p *= p+p; return fract(p); }',
    'float hash12(vec2 p){ vec3 p3 = fract(vec3(p.xyx)*0.1031); p3 += dot(p3, p3.yzx+33.33); return fract((p3.x+p3.y)*p3.z); }',
    'vec2 hash22(vec2 p){ vec3 p3 = fract(vec3(p.xyx)*vec3(0.1031,0.1030,0.0973));',
    '  p3 += dot(p3, p3.yzx+33.33); return fract((p3.xx+p3.yz)*p3.zy); }',
    '',
    'float vnoise(vec2 p){',
    '  vec2 i = floor(p), f = fract(p);',
    '  vec2 u = f*f*(3.0-2.0*f);',
    '  float a = hash12(i), b = hash12(i+vec2(1,0));',
    '  float c = hash12(i+vec2(0,1)), d = hash12(i+vec2(1,1));',
    '  return mix(mix(a,b,u.x), mix(c,d,u.x), u.y);',
    '}',
    '',
    'float fbm(vec2 p, int oct){',
    '  float s = 0.0, a = 0.5;',
    '  for(int i=0;i<6;i++){ if(i>=oct) break; s += vnoise(p)*a; p *= 2.02; a *= 0.5; }',
    '  return s;',
    '}',
    '',
    '// Filmic ACES fit (Narkowicz). Cheap and holds highlights together.',
    'vec3 aces(vec3 x){',
    '  const float a=2.51, b=0.03, c=2.43, d=0.59, e=0.14;',
    '  return clamp((x*(a*x+b))/(x*(c*x+d)+e), 0.0, 1.0);',
    '}',
    'vec3 srgbEncode(vec3 c){ return pow(max(c,vec3(0.0)), vec3(1.0/2.2)); }',
    'vec3 srgbDecode(vec3 c){ return pow(max(c,vec3(0.0)), vec3(2.2)); }',
    ''
  ].join('\n');

  // Physically based direct lighting: GGX specular + Lambert diffuse.
  var BRDF = [
    'float D_GGX(float NoH, float a){',
    '  float a2 = a*a;',
    '  float d = NoH*NoH*(a2-1.0)+1.0;',
    '  return a2/max(PI*d*d, 1e-7);',
    '}',
    'float V_Smith(float NoV, float NoL, float a){',
    '  float a2 = a*a;',
    '  float gv = NoL*sqrt(NoV*NoV*(1.0-a2)+a2);',
    '  float gl = NoV*sqrt(NoL*NoL*(1.0-a2)+a2);',
    '  return 0.5/max(gv+gl, 1e-6);',
    '}',
    'vec3 F_Schlick(vec3 f0, float u){',
    '  float f = pow(1.0-u, 5.0);',
    '  return f0 + (vec3(1.0)-f0)*f;',
    '}',
    ''
  ].join('\n');

  // Analytic sky, shared by the sky dome and by ambient/reflection lookups.
  var SKYFN = [
    'vec3 skyColor(vec3 dir, vec3 sunDir, vec3 sunCol, vec3 zenith, vec3 horizon, float turb){',
    '  float t = clamp(dir.y*0.5+0.5, 0.0, 1.0);',
    '  float h = pow(1.0 - max(dir.y, 0.0), 6.0);',
    '  vec3 col = mix(horizon, zenith, pow(clamp(dir.y,0.0,1.0), 0.45));',
    '  col = mix(col, horizon*1.08, h*0.6);',
    '  // Mie-ish forward scattering halo around the sun.',
    '  float cosT = clamp(dot(dir, sunDir), -1.0, 1.0);',
    '  float mie = pow(max(cosT, 0.0), 8.0);',
    '  col += sunCol * mie * 0.28 * turb;',
    '  col += sunCol * pow(max(cosT,0.0), 160.0) * 0.55;',
    '  // Below-horizon fill so reflections never go black.',
    '  col = mix(col, horizon*0.35, smoothstep(0.0, -0.25, dir.y));',
    '  return col;',
    '}',
    ''
  ].join('\n');

  var SHADOWFN = [
    'float sampleShadowMap(sampler2D sm, vec3 c, vec2 texel, float bias){',
    '  if(c.x<0.001||c.x>0.999||c.y<0.001||c.y>0.999||c.z>1.0) return 1.0;',
    '  float s = 0.0;',
    '  for(int y=-1;y<=1;y++){',
    '    for(int x=-1;x<=1;x++){',
    '      float d = texture(sm, c.xy + vec2(float(x),float(y))*texel).r;',
    '      s += (c.z - bias > d) ? 0.0 : 1.0;',
    '    }',
    '  }',
    '  return s/9.0;',
    '}',
    'float sampleShadowMapWide(sampler2D sm, vec3 c, vec2 texel, float bias){',
    '  if(c.x<0.001||c.x>0.999||c.y<0.001||c.y>0.999||c.z>1.0) return 1.0;',
    '  float s = 0.0;',
    '  for(int y=-2;y<=2;y++){',
    '    for(int x=-2;x<=2;x++){',
    '      float d = texture(sm, c.xy + vec2(float(x),float(y))*texel).r;',
    '      s += (c.z - bias > d) ? 0.0 : 1.0;',
    '    }',
    '  }',
    '  return s/25.0;',
    '}',
    ''
  ].join('\n');

  /* ------------------------------------------------------------ main pass */

  S.mainVS = [
    '#version 300 es',
    'precision highp float;',
    'precision highp int;',
    '',
    'in vec3 aPos;',
    'in vec3 aNormal;',
    'in vec2 aUV;',
    'in vec3 aColor;',
    '#ifdef INSTANCED',
    'in vec4 aIM0; in vec4 aIM1; in vec4 aIM2; in vec4 aIM3;',
    'in vec3 aITint;',
    '#endif',
    '',
    'uniform mat4 uProj;',
    'uniform mat4 uView;',
    'uniform mat4 uModel;',
    'uniform mat4 uNormalMat;',
    'uniform mat4 uLightVP0;',
    'uniform mat4 uLightVP1;',
    'uniform float uTime;',
    'uniform int uMatType;',
    'uniform vec3 uWindPhase;',
    '',
    'out vec3 vWorld;',
    'out vec3 vNormal;',
    'out vec2 vUV;',
    'out vec3 vColor;',
    'out vec4 vShadow0;',
    'out vec4 vShadow1;',
    'out float vViewDepth;',
    '',
    'void main(){',
    '  mat4 model;',
    '  vec3 tint;',
    '#ifdef INSTANCED',
    '  model = mat4(aIM0, aIM1, aIM2, aIM3);',
    '  tint = aITint;',
    '#else',
    '  model = uModel;',
    '  tint = vec3(1.0);',
    '#endif',
    '  vec3 p = aPos;',
    '  // Foliage sway: derived from height up the trunk, so the vertex',
    '  // colour stays free to carry the leaf albedo.',
    '  if(uMatType == 9){',
    '    float sway = clamp((p.y - 1.35) / 4.4, 0.0, 1.0);',
    '    sway *= sway;',
    '    float ph = uWindPhase.x + p.x*0.35 + p.z*0.27;',
    '    p.x += sin(ph)*sway*0.22 + sin(ph*2.7)*sway*0.06;',
    '    p.z += cos(ph*0.83)*sway*0.18;',
    '  }',
    '  vec4 world = model * vec4(p, 1.0);',
    '  vWorld = world.xyz;',
    '#ifdef INSTANCED',
    '  vNormal = normalize(mat3(model) * aNormal);',
    '#else',
    '  vNormal = normalize((uNormalMat * vec4(aNormal, 0.0)).xyz);',
    '#endif',
    '  vUV = aUV;',
    '  vColor = aColor * tint;',
    '  vShadow0 = uLightVP0 * world;',
    '  vShadow1 = uLightVP1 * world;',
    '  vec4 viewPos = uView * world;',
    '  vViewDepth = -viewPos.z;',
    '  gl_Position = uProj * viewPos;',
    '}'
  ].join('\n');

  S.mainFS = [
    '#version 300 es',
    'precision highp float;',
    'precision highp int;',
    'precision highp sampler2D;',
    '',
    'in vec3 vWorld;',
    'in vec3 vNormal;',
    'in vec2 vUV;',
    'in vec3 vColor;',
    'in vec4 vShadow0;',
    'in vec4 vShadow1;',
    'in float vViewDepth;',
    '',
    'out vec4 fragColor;',
    '',
    'uniform vec3 uCamPos;',
    'uniform vec3 uSunDir;',
    'uniform vec3 uSunColor;',
    'uniform vec3 uSkyZenith;',
    'uniform vec3 uSkyHorizon;',
    'uniform vec3 uGroundAmb;',
    'uniform float uTurbidity;',
    '',
    'uniform vec3 uBaseColor;',
    'uniform float uRoughness;',
    'uniform float uMetallic;',
    'uniform vec3 uEmissive;',
    'uniform float uClearcoat;',
    'uniform float uOpacity;',
    'uniform int uMatType;',
    'uniform float uTime;',
    'uniform float uDetail;',
    '',
    'uniform sampler2D uShadow0;',
    'uniform sampler2D uShadow1;',
    'uniform vec2 uShadowTexel0;',
    'uniform vec2 uShadowTexel1;',
    'uniform float uShadowSplit;',
    'uniform int uShadowQuality;',
    '',
    'uniform vec3 uFogColor;',
    'uniform float uFogDensity;',
    'uniform float uFogHeight;',
    'uniform float uExposure;',
    '',
    'uniform int uHeadlights;',
    'uniform vec3 uHeadPos;',
    'uniform vec3 uHeadDir;',
    '',
    COMMON,
    BRDF,
    SKYFN,
    SHADOWFN,
    '',
    '// ---- procedural surface detail -------------------------------------',
    'vec3 asphalt(vec2 uv, out float rough){',
    '  float g = fbm(uv*7.0, 4);',
    '  float speck = step(0.82, hash12(floor(uv*160.0)));',
    '  vec3 c = mix(vec3(0.052,0.053,0.058), vec3(0.105,0.104,0.11), g);',
    '  c += speck*0.09;',
    '  rough = mix(0.62, 0.86, g);',
    '  return c;',
    '}',
    'vec3 grassTex(vec2 uv, out float rough){',
    '  float n = fbm(uv*5.0, 4);',
    '  float n2 = vnoise(uv*38.0);',
    '  vec3 dry = vec3(0.30,0.30,0.14);',
    '  vec3 lush = vec3(0.085,0.19,0.062);',
    '  vec3 c = mix(lush, dry, clamp(n*1.25,0.0,1.0));',
    '  c *= 0.82 + n2*0.36;',
    '  rough = 0.92;',
    '  return c;',
    '}',
    'vec3 rockTex(vec2 uv, out float rough){',
    '  float n = fbm(uv*4.0, 5);',
    '  float strat = sin(uv.y*9.0 + n*5.0)*0.5+0.5;',
    '  vec3 c = mix(vec3(0.20,0.185,0.17), vec3(0.40,0.385,0.36), n);',
    '  c = mix(c, c*0.74, strat*0.45);',
    '  rough = 0.85;',
    '  return c;',
    '}',
    'vec3 dirtTex(vec2 uv, out float rough){',
    '  float n = fbm(uv*6.0, 4);',
    '  vec3 c = mix(vec3(0.24,0.175,0.115), vec3(0.40,0.31,0.21), n);',
    '  rough = 0.95;',
    '  return c;',
    '}',
    '',
    'void main(){',
    '  vec3 N = normalize(vNormal);',
    '  vec3 V = normalize(uCamPos - vWorld);',
    '  if(!gl_FrontFacing) N = -N;',
    '',
    '  vec3 albedo = uBaseColor * vColor;',
    '  float rough = uRoughness;',
    '  float metal = uMetallic;',
    '  float clearcoat = uClearcoat;',
    '  vec3 emis = uEmissive;',
    '  float alpha = uOpacity;',
    '',
    '  // ---------------- terrain: blend four procedural surfaces ---------',
    '  if(uMatType == 3){',
    '    vec2 uv = vWorld.xz * 0.05;',
    '    float wRoad = vColor.r;',
    '    float wRock = vColor.b;',
    '    float wDirt = clamp(1.0 - vColor.g - vColor.r - vColor.b, 0.0, 1.0);',
    '    float wGrass = clamp(vColor.g, 0.0, 1.0);',
    '    float rr, rg, rk, rd;',
    '    vec3 cRoad = asphalt(uv*2.0, rr);',
    '    vec3 cGrass = grassTex(uv, rg);',
    '    vec3 cRock = rockTex(uv*0.7, rk);',
    '    vec3 cDirt = dirtTex(uv*1.4, rd);',
    '    float tot = max(wRoad + wGrass + wRock + wDirt, 1e-4);',
    '    albedo = (cRoad*wRoad + cGrass*wGrass + cRock*wRock + cDirt*wDirt)/tot;',
    '    rough = (rr*wRoad + rg*wGrass + rk*wRock + rd*wDirt)/tot;',
    '    // Slope darkening + a hint of wetness in the road ruts.',
    '    float slope = 1.0 - clamp(N.y, 0.0, 1.0);',
    '    albedo *= 1.0 - slope*0.18;',
    '    metal = 0.0;',
    '  }',
    '  // ---------------- car paint: metallic flake + clearcoat -----------',
    '  else if(uMatType == 1){',
    '    float flake = hash12(floor(vUV*900.0))*0.5 + hash12(floor(vUV*2300.0))*0.5;',
    '    albedo *= 0.94 + flake*0.12;',
    '    rough = clamp(uRoughness - flake*0.05, 0.03, 1.0);',
    '    clearcoat = max(clearcoat, 0.85);',
    '  }',
    '  // ---------------- glass -------------------------------------------',
    '  else if(uMatType == 2){',
    '    rough = 0.045;',
    '    metal = 0.0;',
    '    clearcoat = 1.0;',
    '  }',
    '  // ---------------- tyre rubber -------------------------------------',
    '  else if(uMatType == 7){',
    '    float n = vnoise(vUV*64.0);',
    '    albedo = vec3(0.028,0.028,0.031)*(0.8+n*0.5);',
    '    rough = 0.88 - n*0.12;',
    '    metal = 0.0;',
    '  }',
    '  // ---------------- water --------------------------------------------',
    '  else if(uMatType == 6){',
    '    vec2 p = vWorld.xz;',
    '    float t = uTime;',
    '    vec3 nn = vec3(0.0);',
    '    nn.x += sin(p.x*0.28 + t*1.10)*0.055 + sin(p.x*0.83 - p.y*0.41 + t*1.70)*0.028;',
    '    nn.z += cos(p.y*0.31 - t*0.90)*0.055 + cos(p.y*0.77 + p.x*0.37 - t*1.40)*0.026;',
    '    nn.x += (fbm(p*0.55 + vec2(t*0.25, -t*0.18), 3)-0.5)*0.10;',
    '    nn.z += (fbm(p*0.55 + vec2(-t*0.21, t*0.24), 3)-0.5)*0.10;',
    '    N = normalize(vec3(nn.x, 1.0, nn.z));',
    '    albedo = vec3(0.016,0.048,0.062);',
    '    rough = 0.035;',
    '    metal = 0.0;',
    '  }',
    '  // ---------------- skin / cloth (the driver) ------------------------',
    '  else if(uMatType == 5){',
    '    rough = clamp(uRoughness, 0.45, 1.0);',
    '    metal = 0.0;',
    '  }',
    '  // ---------------- decal: per-vertex alpha (tyre marks) -------------',
    '  else if(uMatType == 10){',
    '    albedo = uBaseColor;',
    '    alpha = uOpacity * clamp(vColor.r, 0.0, 1.0);',
    '    rough = 0.96;',
    '    metal = 0.0;',
    '  }',
    '  // ---------------- emissive (lights, UI markers) --------------------',
    '  else if(uMatType == 4){',
    '    fragColor = vec4(albedo + emis, alpha);',
    '    return;',
    '  }',
    '',
    '  // ------------------------------- shadowing --------------------------',
    '  float shadow = 1.0;',
    '  if(uShadowQuality > 0){',
    '    if(vViewDepth < uShadowSplit){',
    '      vec3 c = vShadow0.xyz / vShadow0.w * 0.5 + 0.5;',
    '      float b = 0.0016 + 0.004*(1.0 - clamp(dot(N, uSunDir),0.0,1.0));',
    '      shadow = (uShadowQuality > 1)',
    '        ? sampleShadowMapWide(uShadow0, c, uShadowTexel0, b)',
    '        : sampleShadowMap(uShadow0, c, uShadowTexel0, b);',
    '    } else {',
    '      vec3 c = vShadow1.xyz / vShadow1.w * 0.5 + 0.5;',
    '      float b = 0.0030 + 0.008*(1.0 - clamp(dot(N, uSunDir),0.0,1.0));',
    '      shadow = sampleShadowMap(uShadow1, c, uShadowTexel1, b);',
    '      // Fade the far cascade out rather than popping to lit.',
    '      float fade = smoothstep(uShadowSplit*3.4, uShadowSplit*4.0, vViewDepth);',
    '      shadow = mix(shadow, 1.0, fade);',
    '    }',
    '  }',
    '',
    '  // ------------------------------- lighting ---------------------------',
    '  vec3 L = uSunDir;',
    '  vec3 H = normalize(L + V);',
    '  float NoL = clamp(dot(N, L), 0.0, 1.0);',
    '  float NoV = clamp(dot(N, V), 1e-4, 1.0);',
    '  float NoH = clamp(dot(N, H), 0.0, 1.0);',
    '  float VoH = clamp(dot(V, H), 0.0, 1.0);',
    '',
    '  float a = max(rough*rough, 0.002);',
    '  vec3 f0 = mix(vec3(0.04), albedo, metal);',
    '  vec3 F = F_Schlick(f0, VoH);',
    '  float D = D_GGX(NoH, a);',
    '  float Vs = V_Smith(NoV, NoL, a);',
    '  vec3 spec = D * Vs * F;',
    '  vec3 kd = (vec3(1.0) - F) * (1.0 - metal);',
    '  vec3 direct = (kd * albedo / PI + spec) * uSunColor * NoL * shadow;',
    '',
    '  // Hemisphere ambient + a crude specular probe from the analytic sky.',
    '  float hemi = N.y*0.5 + 0.5;',
    '  vec3 ambDiff = mix(uGroundAmb, uSkyZenith, hemi);',
    '  vec3 R = reflect(-V, N);',
    '  vec3 probe = skyColor(R, uSunDir, uSunColor, uSkyZenith, uSkyHorizon, uTurbidity);',
    '  // Rough surfaces converge on the flat ambient term.',
    '  probe = mix(probe, ambDiff, clamp(rough*1.15, 0.0, 1.0));',
    '  // Roughness-aware ambient Fresnel. A rough surface does not mirror',
    '  // the sky at grazing angles; treating it as if it does washes every',
    '  // near-horizontal surface out to a flat sky blue, which is exactly',
    '  // what a road seen down its length would suffer from.',
    '  float fresAmb = pow(1.0 - NoV, 5.0) * (1.0 - rough);',
    '  vec3 specColor = mix(f0, max(vec3(1.0 - rough), f0), fresAmb);',
    '  vec3 ambSpec = probe * specColor * (1.0 - rough) * (1.0 - rough * 0.55);',
    '  float ao = mix(1.0, clamp(hemi*1.3, 0.35, 1.0), 0.55);',
    '  vec3 ambient = (ambDiff * albedo * (1.0 - metal) + ambSpec) * ao;',
    '  // Keep a little ambient occlusion from the shadow term so shadowed',
    '  // surfaces do not float in uniform sky light.',
    '  ambient *= mix(0.62, 1.0, shadow);',
    '',
    '  vec3 color = direct + ambient + emis;',
    '',
    '  // Clearcoat lobe: a second, much tighter specular on top.',
    '  if(clearcoat > 0.001){',
    '    float ca = max(0.045*0.045, 0.0016);',
    '    float cD = D_GGX(NoH, ca);',
    '    float cV = V_Smith(NoV, NoL, ca);',
    '    float cF = 0.04 + 0.96*pow(1.0-VoH, 5.0);',
    '    color += vec3(cD*cV*cF) * uSunColor * NoL * shadow * clearcoat;',
    '    vec3 ccProbe = skyColor(R, uSunDir, uSunColor, uSkyZenith, uSkyHorizon, uTurbidity);',
    '    color += ccProbe * (0.04 + 0.96*pow(1.0-NoV,5.0)) * clearcoat * 0.55;',
    '  }',
    '',
    '  // Glass: view-dependent opacity so it reads as a real pane.',
    '  if(uMatType == 2){',
    '    float fres = 0.06 + 0.94*pow(1.0 - NoV, 5.0);',
    '    alpha = clamp(uOpacity + fres*0.72, 0.0, 1.0);',
    '    color += skyColor(R, uSunDir, uSunColor, uSkyZenith, uSkyHorizon, uTurbidity) * fres * 0.9;',
    '  }',
    '  if(uMatType == 6){',
    '    float fres = 0.02 + 0.98*pow(1.0 - NoV, 5.0);',
    '    alpha = clamp(0.62 + fres*0.38, 0.0, 1.0);',
    '  }',
    '',
    '  // ------------------------------- headlight pool ----------------------',
    '  if(uHeadlights == 1){',
    '    vec3 toS = vWorld - uHeadPos;',
    '    float d = length(toS);',
    '    vec3 sd = toS/max(d,1e-4);',
    '    float cone = smoothstep(0.86, 0.985, dot(sd, uHeadDir));',
    '    float atten = 1.0/(1.0 + d*d*0.012);',
    '    float lam = clamp(dot(N, -sd), 0.0, 1.0);',
    '    color += albedo * vec3(1.0,0.96,0.88) * cone * atten * lam * 2.6;',
    '  }',
    '',
    '  // ------------------------------- fog ---------------------------------',
    '  float heightFalloff = exp(-max(vWorld.y - uFogHeight, 0.0) * 0.022);',
    '  float fogAmt = 1.0 - exp(-vViewDepth * uFogDensity * heightFalloff);',
    '  fogAmt = clamp(fogAmt, 0.0, 1.0);',
    '  // Sun-facing fog picks up inscatter — cheap aerial perspective.',
    '  float sunAmt = pow(clamp(dot(normalize(vWorld - uCamPos), uSunDir), 0.0, 1.0), 6.0);',
    '  vec3 fogCol = mix(uFogColor, uSunColor*0.85 + uFogColor*0.4, sunAmt*0.55);',
    '  color = mix(color, fogCol, fogAmt);',
    '',
    '  fragColor = vec4(color * uExposure, alpha);',
    '}'
  ].join('\n');

  /* ------------------------------------------------------------ depth pass */

  S.depthVS = [
    '#version 300 es',
    'precision highp float;',
    'in vec3 aPos;',
    '#ifdef INSTANCED',
    'in vec4 aIM0; in vec4 aIM1; in vec4 aIM2; in vec4 aIM3;',
    '#endif',
    'uniform mat4 uLightVP;',
    'uniform mat4 uModel;',
    'void main(){',
    '#ifdef INSTANCED',
    '  mat4 model = mat4(aIM0, aIM1, aIM2, aIM3);',
    '#else',
    '  mat4 model = uModel;',
    '#endif',
    '  gl_Position = uLightVP * model * vec4(aPos, 1.0);',
    '}'
  ].join('\n');

  S.depthFS = [
    '#version 300 es',
    'precision highp float;',
    'out vec4 fragColor;',
    'void main(){ fragColor = vec4(1.0); }'
  ].join('\n');

  /* ------------------------------------------------------------------ sky */

  S.skyVS = [
    '#version 300 es',
    'precision highp float;',
    'in vec2 aPos;',
    'uniform mat4 uInvViewProj;',
    'uniform vec3 uCamPos;',
    'out vec3 vRay;',
    'out vec2 vUV;',
    'void main(){',
    '  vUV = aPos*0.5 + 0.5;',
    '  vec4 near = uInvViewProj * vec4(aPos, -1.0, 1.0);',
    '  vec4 far  = uInvViewProj * vec4(aPos,  1.0, 1.0);',
    '  vRay = normalize(far.xyz/far.w - near.xyz/near.w);',
    '  gl_Position = vec4(aPos, 1.0, 1.0);',
    '}'
  ].join('\n');

  S.skyFS = [
    '#version 300 es',
    'precision highp float;',
    'in vec3 vRay;',
    'in vec2 vUV;',
    'out vec4 fragColor;',
    'uniform vec3 uSunDir;',
    'uniform vec3 uSunColor;',
    'uniform vec3 uSkyZenith;',
    'uniform vec3 uSkyHorizon;',
    'uniform float uTurbidity;',
    'uniform float uTime;',
    'uniform float uCloudAmount;',
    'uniform float uExposure;',
    COMMON,
    SKYFN,
    'void main(){',
    '  vec3 dir = normalize(vRay);',
    '  vec3 col = skyColor(dir, uSunDir, uSunColor, uSkyZenith, uSkyHorizon, uTurbidity);',
    '',
    '  // Cloud layer: project the ray onto a plane well above the camera.',
    '  if(uCloudAmount > 0.001 && dir.y > 0.012){',
    '    vec2 cp = dir.xz / dir.y * 0.55;',
    '    cp += vec2(uTime*0.0035, uTime*0.0021);',
    '    float d1 = fbm(cp*0.55, 5);',
    '    float d2 = fbm(cp*1.35 + 13.7, 4);',
    '    float cover = clamp((d1*0.68 + d2*0.32 - (1.0-uCloudAmount)*0.62) * 2.7, 0.0, 1.0);',
    '    cover *= smoothstep(0.012, 0.16, dir.y);',
    '    // Fake self-shadowing: denser cores read darker underneath.',
    '    float lit = clamp(0.5 + dot(dir, uSunDir)*0.5, 0.0, 1.0);',
    '    vec3 cloudLit = mix(vec3(0.58,0.60,0.66), vec3(1.25,1.20,1.12), lit);',
    '    cloudLit += uSunColor * pow(max(dot(dir,uSunDir),0.0), 24.0) * 0.5;',
    '    vec3 cloudDark = vec3(0.30,0.32,0.38);',
    '    vec3 cloud = mix(cloudDark, cloudLit, clamp(d2*1.3,0.0,1.0));',
    '    col = mix(col, cloud, cover*0.92);',
    '  }',
    '',
    '  // Very subtle dither to kill banding in the gradient.',
    '  col += (hash12(gl_FragCoord.xy)-0.5)*0.004;',
    '  fragColor = vec4(col * uExposure, 1.0);',
    '}'
  ].join('\n');

  /* ------------------------------------------------------------ post chain */

  var POSTVS = [
    '#version 300 es',
    'precision highp float;',
    'in vec2 aPos;',
    'out vec2 vUV;',
    'void main(){ vUV = aPos*0.5+0.5; gl_Position = vec4(aPos, 0.0, 1.0); }'
  ].join('\n');
  S.postVS = POSTVS;

  S.brightFS = [
    '#version 300 es',
    'precision highp float;',
    'in vec2 vUV;',
    'out vec4 fragColor;',
    'uniform sampler2D uTex;',
    'uniform float uThreshold;',
    'uniform float uSoftKnee;',
    'void main(){',
    '  vec3 c = texture(uTex, vUV).rgb;',
    '  float br = max(c.r, max(c.g, c.b));',
    '  float knee = uThreshold*uSoftKnee + 1e-5;',
    '  float soft = clamp(br - uThreshold + knee, 0.0, 2.0*knee);',
    '  soft = soft*soft/(4.0*knee);',
    '  float contrib = max(soft, br - uThreshold)/max(br, 1e-5);',
    '  fragColor = vec4(c*contrib, 1.0);',
    '}'
  ].join('\n');

  S.blurFS = [
    '#version 300 es',
    'precision highp float;',
    'in vec2 vUV;',
    'out vec4 fragColor;',
    'uniform sampler2D uTex;',
    'uniform vec2 uDir;',
    'void main(){',
    '  // 9-tap gaussian folded into 5 bilinear fetches.',
    '  vec3 s = texture(uTex, vUV).rgb * 0.227027;',
    '  vec2 o1 = uDir * 1.3846153846;',
    '  vec2 o2 = uDir * 3.2307692308;',
    '  s += (texture(uTex, vUV + o1).rgb + texture(uTex, vUV - o1).rgb) * 0.3162162162;',
    '  s += (texture(uTex, vUV + o2).rgb + texture(uTex, vUV - o2).rgb) * 0.0702702703;',
    '  fragColor = vec4(s, 1.0);',
    '}'
  ].join('\n');

  S.compositeFS = [
    '#version 300 es',
    'precision highp float;',
    'in vec2 vUV;',
    'out vec4 fragColor;',
    '',
    'uniform sampler2D uScene;',
    'uniform sampler2D uBloom0;',
    'uniform sampler2D uBloom1;',
    'uniform float uBloomStrength;',
    'uniform float uVignette;',
    'uniform float uChroma;',
    'uniform float uGrain;',
    'uniform float uSpeedBlur;',
    'uniform float uTime;',
    'uniform float uExposure;',
    'uniform float uContrast;',
    'uniform float uSaturation;',
    'uniform vec2 uBlurCenter;',
    'uniform float uDamageFlash;',
    'uniform float uSepia;',
    COMMON,
    'void main(){',
    '  vec2 uv = vUV;',
    '  vec2 toC = uv - uBlurCenter;',
    '  float r = length(toC);',
    '',
    '  vec3 col;',
    '  // Radial speed blur: a handful of taps pulled toward the focus point.',
    '  if(uSpeedBlur > 0.002){',
    '    float amt = uSpeedBlur * smoothstep(0.08, 0.72, r);',
    '    vec3 acc = vec3(0.0);',
    '    float wsum = 0.0;',
    '    for(int i=0;i<8;i++){',
    '      float t = float(i)/7.0;',
    '      float w = 1.0 - t*0.65;',
    '      vec2 suv = uv - toC * t * amt;',
    '      acc += texture(uScene, suv).rgb * w;',
    '      wsum += w;',
    '    }',
    '    col = acc/wsum;',
    '  } else {',
    '    col = texture(uScene, uv).rgb;',
    '  }',
    '',
    '  // Chromatic aberration grows toward the frame edge.',
    '  if(uChroma > 0.0001){',
    '    float ca = uChroma * r * r;',
    '    vec2 dirv = normalize(toC + 1e-6);',
    '    col.r = texture(uScene, uv - dirv*ca).r;',
    '    col.b = texture(uScene, uv + dirv*ca).b;',
    '  }',
    '',
    '  // Two bloom mips give a wide, soft falloff without a big kernel.',
    '  vec3 bloom = texture(uBloom0, uv).rgb * 0.62 + texture(uBloom1, uv).rgb * 0.38;',
    '  col += bloom * uBloomStrength;',
    '',
    '  col *= uExposure;',
    '  col = aces(col);',
    '',
    '  // Grade: contrast around mid grey, then saturation.',
    '  col = clamp((col - 0.5) * uContrast + 0.5, 0.0, 1.0);',
    '  float lum = dot(col, vec3(0.2126, 0.7152, 0.0722));',
    '  col = clamp(mix(vec3(lum), col, uSaturation), 0.0, 1.0);',
    '',
    '  if(uSepia > 0.001){',
    '    vec3 sep = vec3(lum*1.07, lum*0.94, lum*0.78);',
    '    col = mix(col, sep, uSepia);',
    '  }',
    '',
    '  // Damage flash — a red pulse at the edges when the car takes a hit.',
    '  if(uDamageFlash > 0.001){',
    '    col = mix(col, vec3(0.55,0.04,0.03), uDamageFlash * smoothstep(0.18, 0.85, r));',
    '  }',
    '',
    '  float vig = 1.0 - uVignette * smoothstep(0.28, 1.05, r);',
    '  col *= vig;',
    '',
    '  if(uGrain > 0.0001){',
    '    float g = hash12(gl_FragCoord.xy + fract(uTime)*137.0) - 0.5;',
    '    col += g * uGrain * (1.0 - lum*0.65);',
    '  }',
    '',
    '  col += (hash12(gl_FragCoord.xy*1.7 + 3.0)-0.5)*0.0025;',
    '  fragColor = vec4(srgbEncode(col), 1.0);',
    '}'
  ].join('\n');

  S.blitFS = [
    '#version 300 es',
    'precision highp float;',
    'in vec2 vUV;',
    'out vec4 fragColor;',
    'uniform sampler2D uTex;',
    'void main(){ fragColor = texture(uTex, vUV); }'
  ].join('\n');

  // Prepend #define lines just after the #version directive.
  S.withDefines = function (src, defines) {
    if (!defines || !defines.length) return src;
    var lines = src.split('\n');
    var out = [lines[0]];
    for (var i = 0; i < defines.length; i++) out.push('#define ' + defines[i]);
    for (var j = 1; j < lines.length; j++) out.push(lines[j]);
    return out.join('\n');
  };

})();
